//! TVM-FFI dispatch-table codegen helpers.
//!
//! AOT-compiled CuTeDSL kernels land as `.o` files whose entry points are
//! `__tvm_ffi_<name>` TVM-FFI symbols. Rust callers need two things to
//! invoke them: `extern "C"` declarations (so rustc knows the ABI) and a
//! runtime lookup function that turns a key → function pointer.
//!
//! Both `cula` and `fa4` previously had ~60 lines of inline codegen in
//! their `build.rs` to emit that glue from a `manifest.json` file listing
//! compiled variants. The **shape** of their lookup function differs
//! (cuLA keys by `(name, arch)`, fa4 by a struct-tuple of shape params),
//! so this module doesn't try to emit the full lookup for the caller.
//! Instead it exposes the pieces — manifest parsing, extern-block
//! emission, stub generation — and lets each consumer assemble them
//! around its own `match` arms.
//!
//! ## Typical usage
//!
//! ```ignore
//! use prelude_kernelbuild::dispatch;
//! use std::fmt::Write;
//!
//! let variants = dispatch::collect_manifests(&kernels_dir);
//! let dispatch_path = out_dir.join("cula_dsl_dispatch.rs");
//!
//! if variants.is_empty() {
//!     std::fs::write(&dispatch_path, dispatch::stub_lookup(
//!         "pub(crate) fn lookup_dsl(_kernel_type: &str, _key: &str, _arch: u32) \
//!          -> Option<crate::dsl::TVMSafeCallFn>",
//!     ))?;
//!     return Ok(());
//! }
//!
//! let symbols: Vec<&str> = variants.iter()
//!     .filter_map(|v| v["symbol"].as_str())
//!     .collect();
//!
//! let mut code = dispatch::header_comment();
//! code.push_str(&dispatch::tvm_ffi_extern_block(
//!     symbols.iter().copied(),
//!     "crate::dsl::TVMFFIAny",
//! ));
//!
//! // Caller generates the lookup body — this is where per-crate
//! // knowledge about the key shape lives.
//! writeln!(code, "pub(crate) fn lookup_dsl(...) -> Option<...> {{").unwrap();
//! // ... emit match arms ...
//! writeln!(code, "}}").unwrap();
//!
//! std::fs::write(&dispatch_path, code)?;
//! ```

use std::collections::BTreeSet;
use std::fmt::Write as FmtWrite;
use std::path::Path;

use serde_json::Value;

use crate::build_log;

/// Walk per-arch subdirectories of `kernels_dir`, read each
/// `manifest.json`, and return a flat list of every variant across all
/// archs. Also falls back to `kernels_dir/manifest.json` directly for
/// the old single-manifest layout that some crates still use.
///
/// The per-arch layout is:
///
/// ```text
/// kernels_dir/
///   sm_90/
///     <foo.o>
///     manifest.json   ← {"archs": [90], "variants": [...]}
///   sm_100/
///     <foo.o>
///     manifest.json
/// ```
///
/// Variants are returned in the order they appear in each manifest
/// file; callers that care about deterministic dispatch should sort or
/// dedup afterwards.
pub fn collect_manifests(kernels_dir: &Path) -> Vec<Value> {
    let mut variants: Vec<Value> = Vec::new();

    if let Ok(entries) = std::fs::read_dir(kernels_dir) {
        for entry in entries.flatten() {
            let arch_dir = entry.path();
            if !arch_dir.is_dir() {
                continue;
            }
            let manifest_path = arch_dir.join("manifest.json");
            let Ok(manifest_str) = std::fs::read_to_string(&manifest_path) else {
                continue;
            };
            let Ok(manifest) = serde_json::from_str::<Value>(&manifest_str) else {
                continue;
            };
            let Some(arr) = manifest["variants"].as_array() else {
                continue;
            };
            variants.extend(arr.iter().cloned());
        }
    }

    if variants.is_empty() {
        let manifest_path = kernels_dir.join("manifest.json");
        if let Ok(manifest_str) = std::fs::read_to_string(&manifest_path) {
            if let Ok(manifest) = serde_json::from_str::<Value>(&manifest_str) {
                if let Some(arr) = manifest["variants"].as_array() {
                    variants.extend(arr.iter().cloned());
                }
            }
        }
    }

    variants
}

/// Standard generated-file header comment. Every generated dispatch
/// file starts with this so it's obvious it shouldn't be hand-edited.
pub fn header_comment() -> String {
    "// AUTO-GENERATED by build.rs via prelude-kernelbuild — do not edit\n\n".to_string()
}

/// Emit an `unsafe extern "C" { ... }` block declaring every symbol in
/// `symbols` with the standard TVM-FFI callable signature:
///
/// ```text
/// fn <symbol>(
///     handle: *mut std::ffi::c_void,
///     args: *const <TVMFFIAny>,
///     num_args: i32,
///     ret: *mut <TVMFFIAny>,
/// ) -> i32;
/// ```
///
/// `tvmffi_any_path` is the fully-qualified path the consumer wants
/// rendered for the `TVMFFIAny` type (usually something like
/// `crate::dsl::TVMFFIAny` or `prelude_cutedsl::TVMFFIAny`). Symbols are
/// deduped — if the same symbol appears twice across manifests, only
/// the first declaration is emitted.
pub fn tvm_ffi_extern_block<'a, I: IntoIterator<Item = &'a str>>(
    symbols: I,
    tvmffi_any_path: &str,
) -> String {
    let mut code = String::new();
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    writeln!(code, "unsafe extern \"C\" {{").unwrap();
    for sym in symbols {
        if !seen.insert(sym) {
            continue;
        }
        writeln!(
            code,
            "    fn {sym}(\n        \
                handle: *mut std::ffi::c_void,\n        \
                args: *const {tvmffi_any_path},\n        \
                num_args: i32,\n        \
                ret: *mut {tvmffi_any_path},\n    \
             ) -> i32;"
        )
        .unwrap();
    }
    writeln!(code, "}}\n").unwrap();
    code
}

/// Emit a stub lookup function that always returns `None`. Used when no
/// kernels were compiled (DSL feature off, or compile failed) — the
/// consumer crate's runtime code gracefully falls through to a CPU or
/// composed path when the registry returns nothing.
///
/// `fn_signature` is the full `pub(crate) fn lookup(...)` signature line
/// without a trailing `{` — e.g.
/// `"pub(crate) fn lookup_dsl(_kernel_type: &str, _key: &str, _arch: u32)
///   -> Option<crate::dsl::TVMSafeCallFn>"`.
pub fn stub_lookup(fn_signature: &str) -> String {
    format!("{header}{fn_signature} {{ None }}\n", header = header_comment())
}

/// Convenience: log how many variants were wired into a dispatch table
/// so `cargo build` warnings tell the user something useful. Called by
/// consumer build.rs after emitting the code.
pub fn log_generated(crate_label: &str, variant_count: usize) {
    build_log!("{crate_label}: generated dispatch with {variant_count} variants");
}
